name: Validate Jira Key in Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
  push:
    branches: main # check how it can be always the default, either master or main or whatever

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate_jira_key:
    name: Validate Jira key
    runs-on: cx-public-ubuntu-x64
    steps:
      - name: Validate Jira Key
        if: ${{ github.event_name != 'push' }}
        env:
          GH_API_URL: ${{ github.api_url }}
          GH_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.number }}
        run: |
          pr_title=$(curl -s \
                     -H "Accept: application/vnd.github.v3+json" \
                     "$GH_API_URL/repos/$GH_REPOSITORY/pulls/$PR_NUMBER" | \
                     jq -r '.title')

          if [[ ! $pr_title =~ (\(|\[)?[A-Z]+-[0-9]+(,[A-Z]+-[0-9]+)*(\)|\])? ]]; then
            echo "ERROR: Pull request title does not contain a valid Jira key."
            echo "Edit the PR title and retrigger the workflow"
            exit 1
          else
            echo "PR title is valid."
          fi